/**
 * Root Layout — src/app/layout.tsx
 *
 * WHERE: Runs on the server for every request. The html+body tags live here.
 * WHY:   Required by Next.js. Every route is wrapped by this layout.
 * WHAT:  Sets global fonts, metadata, and HTML structure.
 *        Does NOT re-render on navigation — it stays mounted.
 *
 * Note: No 'use client' directive → this is a Server Component.
 * It can safely import fonts, set metadata, and access server-only values.
 */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// next/font downloads fonts at BUILD TIME and serves them locally.
// Zero layout shift, no network request to Google at runtime.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

// Metadata is a Server Component feature — it cannot be in a Client Component.
// Next.js generates the <head> tags from this at build/request time.
export const metadata: Metadata = {
  title: {
    default: "TradeLens",
    // %s is replaced by page-level title segments
    template: "%s | TradeLens",
  },
  description:
    "A professional trading journal and analytics platform for serious traders.",
  keywords: ["trading journal", "trade analytics", "trading performance"],
};

// LayoutProps<'/'> is a globally available type generated by Next.js 16.
// It infers the correct prop types (children, params, named slots) from the
// route path. No import needed — Next.js generates it automatically.
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      // The font variables are CSS custom properties injected by next/font.
      // We apply them to <html> so they cascade to the entire document.
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body>
        {children}
      </body>
    </html>
  );
}

